"""Типы API ИИ-сервиса: запросы, ответы и события журнала сессии.

Общие для ИИ-сервиса и его клиентов, прежде всего платформы. Имена полей в Python — в
snake_case, в JSON — в camelCase.
"""

from .api import (
    TEXT_MAX_LENGTH,
    AcceptedResponse,
    CreateSessionRequest,
    ErrorResponse,
    SelectModelRequest,
    SendMessageRequest,
    SessionEventsResponse,
    SessionListResponse,
)
from .base import ApiModel
from .context import ContextItem, ContextSegment, ContextSegmentKey, SessionContextResponse
from .events import (
    SESSION_EVENT_ADAPTER,
    AssistantMessageEvent,
    AssistantNoteEvent,
    ChildSessionStartedEvent,
    EventBase,
    ModelReplyEvent,
    SessionCompletedEvent,
    SessionEvent,
    SessionFailedEvent,
    StepStartedEvent,
    ToolCallEvent,
    ToolOutcome,
    ToolResultEvent,
    TurnFailedEvent,
    TurnFailureReason,
    TurnFinishedEvent,
    UserMessageEvent,
)
from .mcp import (
    MCP_NAME_PATTERN,
    CreateMcpConnectionRequest,
    HttpTransport,
    ImportMcpConnectionsRequest,
    McpCheckStatus,
    McpConnection,
    McpConnectionListResponse,
    McpImportResponse,
    McpSnapshot,
    McpToolMode,
    McpToolSnapshot,
    McpTransport,
    SseTransport,
    StdioTransport,
    ToggleMcpConnectionRequest,
    UpdateMcpConnectionRequest,
)
from .model_profile import (
    CreateModelProfileRequest,
    ModelAvailability,
    ModelInUseError,
    ModelListResponse,
    ModelProfile,
    ModelSession,
    UpdateModelProfileRequest,
)
from .provider import (
    PROVIDER_NAME_PATTERN,
    SECRET_MASK,
    CreateProviderRequest,
    ModelReference,
    Provider,
    ProviderCheckStatus,
    ProviderInUseError,
    ProviderListResponse,
    ProviderModel,
    ProviderModelsResponse,
    ProviderType,
    Secrets,
    UpdateProviderRequest,
)
from .session import RenameSessionRequest, Session, SessionKind, SessionStatus
from .snapshot import RequestSnapshot, RequestSnapshotContent, SnapshotTool
from .tools import ToolInfo, ToolListResponse, ToolSource

__all__ = [
    "MCP_NAME_PATTERN",
    "PROVIDER_NAME_PATTERN",
    "SECRET_MASK",
    "SESSION_EVENT_ADAPTER",
    "TEXT_MAX_LENGTH",
    "AcceptedResponse",
    "ApiModel",
    "AssistantMessageEvent",
    "AssistantNoteEvent",
    "ChildSessionStartedEvent",
    "ContextItem",
    "ContextSegment",
    "ContextSegmentKey",
    "CreateMcpConnectionRequest",
    "CreateModelProfileRequest",
    "CreateProviderRequest",
    "CreateSessionRequest",
    "ErrorResponse",
    "EventBase",
    "HttpTransport",
    "ImportMcpConnectionsRequest",
    "McpCheckStatus",
    "McpConnection",
    "McpConnectionListResponse",
    "McpImportResponse",
    "McpSnapshot",
    "McpToolMode",
    "McpToolSnapshot",
    "McpTransport",
    "ModelAvailability",
    "ModelInUseError",
    "ModelListResponse",
    "ModelProfile",
    "ModelReference",
    "ModelReplyEvent",
    "ModelSession",
    "Provider",
    "ProviderCheckStatus",
    "ProviderInUseError",
    "ProviderListResponse",
    "ProviderModel",
    "ProviderModelsResponse",
    "ProviderType",
    "RenameSessionRequest",
    "RequestSnapshot",
    "RequestSnapshotContent",
    "Secrets",
    "SelectModelRequest",
    "SendMessageRequest",
    "Session",
    "SessionCompletedEvent",
    "SessionContextResponse",
    "SessionEvent",
    "SessionEventsResponse",
    "SessionFailedEvent",
    "SessionKind",
    "SessionListResponse",
    "SessionStatus",
    "SnapshotTool",
    "SseTransport",
    "StdioTransport",
    "StepStartedEvent",
    "ToggleMcpConnectionRequest",
    "ToolCallEvent",
    "ToolInfo",
    "ToolListResponse",
    "ToolOutcome",
    "ToolResultEvent",
    "ToolSource",
    "TurnFailedEvent",
    "TurnFailureReason",
    "TurnFinishedEvent",
    "UpdateMcpConnectionRequest",
    "UpdateModelProfileRequest",
    "UpdateProviderRequest",
    "UserMessageEvent",
]
